interface Account
{
    void deposit (in long amount);
    void withdraw (in long amount);
    long getBalance ();
	boolean login (in unsigned short pin);
	string getCardNum ();
};
interface Bank
{
	Account getAccount (in string cardNum);
    void createAccount (in string cardNum, in unsigned short pin, in long balance);
	string getName ();
};
