interface Account
{
    void deposit (in float amount, in string bankName);
    void withdraw (in float amount, in string bankName);
    float balance ();
	boolean login (in unsigned short pin);
};
interface Bank
{
    Account create (in string cardNum, in unsigned short pin, in float balance, in string bankName);
};
